//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgentMaster
    {
        public int AgentID { get; set; }
        public string AgentCode { get; set; }
        public string AgentName { get; set; }
        public string AgentStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AgentAadhar { get; set; }
        public string AgentPAN { get; set; }
        public Nullable<int> AgentBankAcctNo { get; set; }
        public string AgentBankName { get; set; }
        public string AgentBankBranch { get; set; }
        public string AgentBankIFSC { get; set; }
        public string AgentSponserCode { get; set; }
        public string AgentSuperSponserCode { get; set; }
    }
}
