//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgreement
    {
        public int AgreementID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> TowerID { get; set; }
        public string TowerName { get; set; }
        public Nullable<int> FlatID { get; set; }
        public string FlatName { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string AgentName { get; set; }
        public string Commission { get; set; }
        public string PaymentMode { get; set; }
        public string Comments { get; set; }
        public string AgreementDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
