//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookingInformation
    {
        public int BookingID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TowerID { get; set; }
        public Nullable<int> FlatID { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> Bhk { get; set; }
        public Nullable<int> Area { get; set; }
        public string Facing { get; set; }
        public Nullable<int> SftRate { get; set; }
        public Nullable<int> HighRiseCharges { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> TotalRate { get; set; }
        public Nullable<int> FinalRate { get; set; }
        public Nullable<int> ClubHouseCharges { get; set; }
        public Nullable<int> GrandRate { get; set; }
        public string PaymentMode { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> BookingAmount { get; set; }
        public Nullable<int> BalanceAmount { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<double> AgentComm { get; set; }
        public Nullable<double> SASComm { get; set; }
        public Nullable<double> SASTDS { get; set; }
        public Nullable<double> SASNet { get; set; }
        public Nullable<int> Aadhar { get; set; }
        public string Name { get; set; }
    }
}
