//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerVisitInfo
    {
        public int VisitID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string AgentName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobile { get; set; }
        public string SelfieURL { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string AddedBy { get; set; }
    }
}
