//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerEnquiry
    {
        public int EnquiryID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<long> Mobile { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Enquiry { get; set; }
        public string Sms { get; set; }
        public string Recipients { get; set; }
        public Nullable<System.DateTime> EnquiryDate { get; set; }
    }
}
