//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlat
    {
        public int FlatID { get; set; }
        public string FlatName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TowerID { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<double> Bhk { get; set; }
        public Nullable<int> Sft { get; set; }
        public string Facing { get; set; }
        public string BookingStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string FlatPlanURL { get; set; }
    
        public virtual tblProject tblProject { get; set; }
        public virtual tblProject tblProject1 { get; set; }
        public virtual tblProject tblProject2 { get; set; }
        public virtual tblTower tblTower { get; set; }
        public virtual tblTower tblTower1 { get; set; }
        public virtual tblTower tblTower2 { get; set; }
    }
}
