//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFranchiseRegistration
    {
        public int RegisterNo { get; set; }
        public Nullable<int> IBOID { get; set; }
        public string IBOName { get; set; }
        public Nullable<int> Country { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> State { get; set; }
        public string StateName { get; set; }
        public Nullable<int> City { get; set; }
        public string CityName { get; set; }
        public Nullable<int> Area { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Duration { get; set; }
        public string ReceiptPath { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
    }
}
