//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFranchiseBooking
    {
        public int ID { get; set; }
        public Nullable<int> FranchiseID { get; set; }
        public Nullable<int> FranchiseOwnerID { get; set; }
        public string FranchiseOwnerName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> TowerID { get; set; }
        public string TowerName { get; set; }
        public Nullable<int> FlatID { get; set; }
        public string FlatName { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<double> Bhk { get; set; }
        public Nullable<int> Area { get; set; }
        public string Facing { get; set; }
        public Nullable<int> SftRate { get; set; }
        public Nullable<int> HighRiseCharges { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> TotalRate { get; set; }
        public Nullable<int> FinalRate { get; set; }
        public Nullable<int> ClubHouseCharges { get; set; }
        public Nullable<int> GrandRate { get; set; }
        public string PaymentMode { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> BookingAmount { get; set; }
        public Nullable<int> BalanceAmount { get; set; }
        public Nullable<System.Guid> BookingID { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
