//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlatWiseAgentCommission
    {
        public int FlatID { get; set; }
        public string FlatName { get; set; }
        public int AgentID { get; set; }
        public string AgentName { get; set; }
        public Nullable<int> AgentCommission { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public Nullable<int> NetBalance { get; set; }
    }
}
