//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIBOAdvanceForm
    {
        public int ID { get; set; }
        public Nullable<int> IBOID { get; set; }
        public string IBOName { get; set; }
        public Nullable<int> SeniorID { get; set; }
        public string SeniorName { get; set; }
        public Nullable<int> DirectorID { get; set; }
        public string DirectorName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> TowerID { get; set; }
        public string TowerName { get; set; }
        public Nullable<int> FlatID { get; set; }
        public string FlatName { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public bool ApprovedByDirector { get; set; }
        public string PaidThrough { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Comment { get; set; }
    }
}
