//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int ID { get; set; }
        public string InvoiceNo { get; set; }
        public string QuotationNo { get; set; }
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierPhone { get; set; }
        public string ExpenseType { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public Nullable<double> CGSTPercentage { get; set; }
        public Nullable<double> CGST { get; set; }
        public Nullable<double> SGSTPercentage { get; set; }
        public Nullable<double> SGST { get; set; }
        public Nullable<double> IGSTPercentage { get; set; }
        public Nullable<double> IGST { get; set; }
        public Nullable<double> NetValue { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
