//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNew
    {
        public int NewsID { get; set; }
        public string News { get; set; }
        public string NewsDate { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
