//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentVoucher
    {
        public string VoucherNo { get; set; }
        public string InvoiceNo { get; set; }
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierPhone { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ModeOfPayment { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
