//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchemeMaster
    {
        public int SchemeID { get; set; }
        public int ProjectID { get; set; }
        public string SchemeName { get; set; }
        public string SchemeStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> SqFtCost { get; set; }
        public Nullable<int> PaymentTimePeriod { get; set; }
        public Nullable<int> DownPayment { get; set; }
        public Nullable<int> DownPaymentTimePeriod { get; set; }
    }
}
