//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSiteVisitInfo
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string AgentName { get; set; }
        public Nullable<int> ImmediateSeniorID { get; set; }
        public string ImmediateSeniorName { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> NoOfCustomers { get; set; }
        public string CustomerMobile { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string DateOfVisit { get; set; }
        public Nullable<bool> TermsAccepted { get; set; }
        public string Status { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public string ApprovedOrRejectedBy { get; set; }
        public string AgentMobile { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string DriverName { get; set; }
    }
}
